spring:
  datasource:
    url: jdbc:mysql://localhost/jzzz
    username: jzzzuser
    password: jzzzuserpw
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 9082