spring:
  datasource:
    url: jdbc:mysql://localhost:3307/legalfly?serverTimezone=UTC
    username: "legalflyuser"
    password: "legalflyuserpw"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

